// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwX8XGtf5-haWBbV6G2UeRGYUTnW9Irs',
    appId: '1:780347999304:web:977a6547f8cefe4bab447d',
    messagingSenderId: '780347999304',
    projectId: 'condogenius-125bd',
    authDomain: 'condogenius-125bd.firebaseapp.com',
    storageBucket: 'condogenius-125bd.appspot.com',
    measurementId: 'G-G33K85G275',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYi55nWskf3_4OciXfoOgzdBT9dJnuBCk',
    appId: '1:780347999304:android:8ce38bc8e40132e4ab447d',
    messagingSenderId: '780347999304',
    projectId: 'condogenius-125bd',
    storageBucket: 'condogenius-125bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLYdWL80XBNY0y_snnrJl3gpuiwyRyB0',
    appId: '1:780347999304:ios:7ac1d7414a3c401eab447d',
    messagingSenderId: '780347999304',
    projectId: 'condogenius-125bd',
    storageBucket: 'condogenius-125bd.appspot.com',
    iosBundleId: 'com.example.condoGeniusBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLYdWL80XBNY0y_snnrJl3gpuiwyRyB0',
    appId: '1:780347999304:ios:a41e999c90167cb0ab447d',
    messagingSenderId: '780347999304',
    projectId: 'condogenius-125bd',
    storageBucket: 'condogenius-125bd.appspot.com',
    iosBundleId: 'com.example.condoGeniusBeta.RunnerTests',
  );
}
